# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 102df23eb1d5d7ad3a8d16a797ff6b4b3578abd089ef53a47f56c620e112b72aba570cc818ab2804c2ce3e4f4f0b924de78e4c81e876afd654f4b3de086c5fc9

test:
  secret_key_base: 130c7f667f86f13c298861d9c882a8b49edfef875932c82f612da8e7a7c00e7a0bad6665280d0beb464df95f4787149a710170eb0a8917dd7352c2e6e6659dae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
